- name: add-repos
  command:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
- name: add-zoom-flatpak
  command:
    cmd: flatpak install flathub us.zoom.Zoom --assumeyes
    creates: /var/lib/flatpak/app/us.zoom.Zoom
- name: add-podcasts-flatpak
  command:
    cmd: flatpak install flathub org.gnome.Podcasts --assumeyes
    creates: /var/lib/flatpak/app/org.gnome.Podcasts
- name: ensure-zoom-config-exists
  lineinfile:
    path: /home/e2c/.var/app/us.zoom.Zoom/config/zoomus.conf
    line: [General]
    state: present
    create: yes
- name: set-zoom-locale-to-fr
  lineinfile:
    path: /home/e2c/.var/app/us.zoom.Zoom/config/zoomus.conf
    regexp: '^language='
    line: language=fr
    insertafter: '\[General\]'
    state: present
