- name: add-repos
  command:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: add-flatpaks
  command:
    cmd: flatpack install flathub org.chromium.Chromium 
