- name: create ansible user
  user: 
    name: ansible 
    uid: 900

- name: copy sudoers_ansible
  copy: 
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible 
    owner: root 
    group: root 
    mode: '0440'

- name: ensure lambda user is present
  user:
    name: e2c
    state: present
    groups: admin
